### ISSUE TITLE
CLI: gov store proposal wasm code display issue

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#184]
## Problem Definition
When proposals listed or a single one is displayed via CLI the wasm byte code is rendered byte by byte on a new line. This Is due to the default YAML rendering in `cliCtx.PrintOutput()`.

```yaml
- content:
    wasmproposal:
      title: foo
      description: bar
    creator: cosmos100dejzacpanrldpjjwksjm62shqhyss44jf5xz
    wasm_byte_code:
    - 31
    - 139
    - 8
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 255
    - 236
    - 189
    - 13
    - 148
    - 30
    - 199
    - 113
    - 24
    - 216
    - 213
    - 221
    - 51
    - 223
    - 183
    - 223
    - 204
    - 236
    - 14
...
```

This can be reproduced with
```
# store
wasmcli tx gov submit-proposal wasm-store contract.wasm --title=foo --description=bar --creator=cosmos100dejzacpanrldpjjwksjm62shqhyss44jf5xz --from validator --gas 10000000  -y --chain-id=testing --node=http://localhost:26657 -b block

# list proposals
wasmcli q gov proposals
```

### Workaround
Use json output via `--output json` flag.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
